name: flutter_blue
description: >
  Flutter plugin for connecting and communicating with Bluetooth Low Energy devices,
  on Android and iOS
version: 0.7.8
homepage: https://github.com/BrainCo/flutter_blue
publish_to: http://47.111.166.90:8081

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: "^2.1.1"
  protobuf:
    hosted:
      name: protobuf
      url: http://47.111.166.90:8081
    version: ^1.0.1
  rxdart: "^0.24.0"
  meta: ^1.1.8
  collection: ^1.14.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pauldemarco.flutter_blue
        pluginClass: FlutterBluePlugin
      ios:
        pluginClass: FlutterBluePlugin
